Compilation fix.
Since FFmpeg r12484, libswscale requires EXTERN_PREFIX defined.


git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@26262 b3059339-0415-0410-9bf9-f77b7e298cf2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2296,6 +2296,16 @@ if test "$_runtime_cpudetection" = yes ; then
 fi
 
 
+echocheck "extern symbol prefix"
+cat > $TMPC << EOF
+int ff_extern;
+EOF
+cc_check -c || die "Symbol mangling check failed."
+sym=$(nm -P -g $TMPEXE)
+extern_prefix=${sym%%ff_extern*}
+_def_extern_prefix="#define EXTERN_PREFIX \"$extern_prefix\""
+echores $extern_prefix
+
 
 echocheck "assembler support of -pipe option"
 cat > $TMPC << EOF
@@ -7956,6 +7966,9 @@ $_def_builtin_expect
 #else
 # define attribute_used
 #endif
+
+/* extern symbol prefix */
+$_def_extern_prefix
 
 /* compiler support for named assembler arguments */
 $_def_named_asm_args
