configure: Make --enable-gui print an error
Since compilation with GUI enabled will not succeed, make the
configure option return an error immediately instead of triggering an
obscure compiler error later.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1286,6 +1286,11 @@ for ac_option do
   esac
 done
 
+if test "$_gui" = yes ; then
+  echo "Error: --enable-gui is no longer supported. Use an external frontend if you want a GUI." >&2
+  exit 1
+fi
+
 # Atmos: moved this here, to be correct, if --prefix is specified
 test -z "$_bindir" && _bindir="$_prefix/bin"
 test -z "$_datadir" && _datadir="$_prefix/share/mplayer"
