/etc/mplayer.conf created on install-time based on user responses.
git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@854 b3059339-0415-0410-9bf9-f77b7e298cf2

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,3 +1,53 @@
+#!/bin/sh -e
+# postinst script for mplayer
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see /usr/share/doc/packaging-manual/
+#
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
+
+case "$1" in
+configure)
+#TODO: creating /etc/mplayer.conf, 
+
+
+# Source debconf library.
+. /usr/share/debconf/confmodule
+
+db_subst mplayer/output vo xv, xmga, mga, x11, gl, sdl
+
+db_input high mplayer/output || true
+db_go
+
+if [ -f /etc/mplayer.conf ]; then
+
+db_input high mplayer/overwrite || true
+db_go
+db_get mplayer/overwrite
+ else
+$RET="true"
+fi
+
+	if [ "$RET" = "true" ]; then
+	db_get mplayer/output
+
+	cat <<EOCFG > /etc/mplayer.conf
 ##
 ## MPlayer config file
 ##
@@ -8,7 +58,7 @@
 ## more flexibly here. See below.
 ##
 
-vo=xv			# To specify your default video output see -vo help for
+vo=$RET			# To specify your default video output see -vo help for
 			# valid settings
 
 fs=yes			# Enlarges movie window to your desktop's size.
@@ -90,3 +140,37 @@ ffactor = 1
 ##
 
 #include = /home/gabucino/.mplayer/savage4.conf
+
+
+EOCFG
+
+	fi
+
+
+#db_purge
+db_input medium mplayer/cfgnote || true
+db_go
+
+
+
+# store info in debconf database
+;;
+
+abort-upgrade|abort-remove|abort-deconfigure)
+
+;;
+
+*)
+echo "postinst called with unknown argument \`$1'" >&2
+exit 0
+;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
+
